apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wh82m1g27-python
  janus-idp.io/tekton: wh82m1g27-python
  backstage.io/kubernetes-id: wh82m1g27-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wh82m1g27-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
