apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wh82m1g27-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wh82m1g27-python 
  name: wh82m1g27-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wh82m1g27-python 
